### ISSUE TITLE
Dep Resolving: Cannot choose between the following variants

### ISSUE THREAD

**Issue by MairwunNx** [korlibs/kds#15]
**As I define dependency:**
`implementation 'com.soywiz.korlibs.kds:kds-jvm:1.9.2'`

**Declared repository:**
`maven { url "https://dl.bintray.com/korlibs/korlibs" }`

But gradle said me *no* :D

```
   > Could not resolve com.soywiz.korlibs.kds:kds-jvm:1.9.2.
     Required by:
         project :
      > Cannot choose between the following variants of com.soywiz.korlibs.kds:kds-jvm:1.9.2:
          - jvm-api
          - jvm-runtime
          - metadata-api
```

My project is JVM project, not android, not mp. Thank you! 🎉

**Comment by MairwunNx** [comment]
**It's not your problem, it caused by that code:**

```groovy
    from configurations.internal.collect {
        if (!it.name.startsWith("kotlin")) it.isDirectory() ? it : zipTree(it)
    }
```

But, why, I really don't understand why this code causes this issue.

*I just want to include your library runtime to bundle, but I also can't use Shadow.*

**Comment by MairwunNx** [comment]
I also updated version to `1.10.9` (Latest in your repository), and it resolved my problem.

Also, I think need to update version in readme. Thank you for awesome libraries 🎉

**Comment by RezMike** [comment]
The latest version is specified at the top of readme:
![image](https://user-images.githubusercontent.com/19624167/83879422-cb26a900-a767-11ea-8d43-f367a6269fa4.png)
